// reactjs/src/App.js
import Todo from "./components/Todo";

function App() {
    const TODOS = [
        { name: 'Coding' },
        { name: 'Assignment' },
        { name: 'Study' },
    ]

    return (
        <div className="App">
            <div>
                <h1>TODOS</h1>
                <ul>
                    {
                        TODOS.map((d) => (
                            <Todo name={d.name} />
                        ))
                    }
                </ul>
            </div>
        </div>
    );
}

export default App;

// vuejs/src/App.vue
<script setup>
import Todo from "@/components/Todo.vue";

const TODOS = [
    { name: 'Coding' },
    { name: 'Assignment' },
    { name: 'Study' },
]
</script>

<template>
    <div>
        <h1>TODOS</h1>
        <ul>
            <template v-for="d in TODOS">
                <Todo :name="d.name" />
            </template>
        </ul>
    </div>
</template>
