// reactjs/src/components/Todo.jsx
import {useEffect, useState} from "react";
import S from './Todo.module.css';

const Todo = ({ name }) => {
    const [isChecked, setIsChecked] = useState(false);

    const handleCheck = () => {
        setIsChecked((prev) => !prev);
    }

    useEffect(() => {
        if (isChecked) alert('Checked!');
    }, [isChecked]);

    return (
        <li
            className={isChecked && S['line-through']}
        >
            <input
                type={'checkbox'}
                checked={isChecked}
                onInput={handleCheck}
            />
            {name}
        </li>
    )
}

export default Todo;

// vuejs/src/components/Todo.vue
<script setup>
import {reactive, watch} from "vue";

defineProps({
    name: {
        type: String,
        required: true
    }
})

const state = reactive({
    checked: false
})

const handleCheck = () => {
    state.checked = !state.checked;
}

watch(() => state.checked, () => {
    if (state.checked) alert('Checked!');
})
</script>

<template>
    <li :class="state.checked && 'line-through'">
        <input type="checkbox"
               :checked="state.checked"
               @input="handleCheck"
        />
        {{ name }}
    </li>
</template>

<style scoped>
.line-through {
    text-decoration: line-through;
}
</style>
